version: "3.9"
services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "5000:5000"
    env_file:
      - ./packages/backend/.env
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  postgres:
    image: postgres:15.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: supply_chain_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
