version: "3"
services:
  backend:
    build: ./packages/backend
    ports:
      - "5000:5000"
    env_file:
      - ./packages/backend/.env
  frontend:
    build: ./packages/frontend
    ports:
      - "3000:80"
