export enum PaymentStatus {
  PREPAID = "PREPAID",
  COD = "COD",
}
export enum OrderStatus {
  REQUESTED = "REQUESTED",
  PACKED = "PACKED",
  SHIPPED = "SHIPPED",
  IN_TRANSIT = "IN_TRANSIT",
  DELIVERED = "DELIVERED",
  RETURNED = "RETURNED",
  CANCELLED = "CANCELLED",
}
